ex04 : ex04.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex05 : ex05.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex06 : ex06.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex07 : ex07.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex08 : ex08.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex09 : ex09.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex10 : ex10.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex11 : ex11.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2 -l SDL2_image