ex01 : ex01.c ../engine/util.c ../engine/button.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2 -l SDL2_image -l SDL2_ttf
ex02 : ex02.c ../engine/util.c ../engine/button.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2 -l SDL2_image -l SDL2_ttf
ex03 : ex03.c ../engine/util.c ../engine/button.c ../engine/text_Lable.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2 -l SDL2_image -l SDL2_ttf