ex01 : ex01.c ../engine/graph.c
	gcc -g -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2 -l SDL2_image
ex02 : ex02.c ../engine/graph.c ../engine/core.c ../engine/entity/sprite.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2 -l SDL2_image -l SDL2_ttf