ex01 : ex01.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex02 : ex02.c
	gcc -o $@.exe $^
ex03 : ex03.c
	gcc -o $@.exe $^
ex04 : ex04.c
	gcc -o $@.exe $^
ex05 : ex05.c
	gcc -o $@.exe $^
ex06 : ex06.c
	gcc -o $@.exe $^
ex07 : ex07.c
	gcc -o $@.exe $^
ex08 : ex08.c
	gcc -o $@.exe $^
ex09 : ex09.c
	gcc -o $@.exe $^
ex10 : ex10.c
	gcc -o $@.exe $^
ex11 : ex11.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2
ex12 : ex12.c
	gcc -o $@.exe $^ -l mingw32 -l SDL2main -l SDL2